In [32]:
import numpy as np

Numpy is way better than list because they are way faster in computing

We can create a one dimensional array

In [3]:
array_1 = np.array([1, 2, 3])

print(array_1)

[1 2 3]


## Dimension of an array

In [9]:
a = np.array(8)
a.ndim  # this is a scalar

0

In [12]:
a = np.array([2, 4, 5])
a.ndim # This is a 1-dimensional vector

1

In [13]:
a = np.array([[2,4], [4, 6]])
a.ndim # This is a 2-dimensional matrix 

2

In [16]:
a = np.array([[[2,3],[1,2]]]) # This is a 3-dimensional vector
a.ndim

3

## Type of an array

In [27]:
b = np.array([[3,5]], dtype=np.float64)
b

array([[3., 5.]])

In [25]:
b = np.array([[[3,5,3], [0,3,8], [3,5, -1]]], dtype=np.complex_)
b

array([[[ 3.+0.j,  5.+0.j,  3.+0.j],
        [ 0.+0.j,  3.+0.j,  8.+0.j],
        [ 3.+0.j,  5.+0.j, -1.+0.j]]])

## Shape 

In [26]:
b.shape

(1, 3, 3)

## np zeros


In [34]:
a = np.zeros((3,4,4)) # 3 4*4 matrices
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
c = np.array([[[1,1,1], [2,2,2]],[[3,3,3],[4,4,4]]])
c

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [37]:
c.shape

(2, 2, 3)

In [39]:
c.ndim

3

In [41]:
c = np.array([[[1,1],[2,1]],[[3,4],[0,9]]], dtype=np.complex64)
c

array([[[1.+0.j, 1.+0.j],
        [2.+0.j, 1.+0.j]],

       [[3.+0.j, 4.+0.j],
        [0.+0.j, 9.+0.j]]], dtype=complex64)

In [42]:
c.shape

(2, 2, 2)

## np ones

In [45]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## np arange

In [46]:
a = np.arange(10) # this gives you a list of range(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Array manipulation

In [49]:
a = np.arange(1,101)
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


### np reshape

In [61]:
a = np.arange(1,101)
b = a.reshape(2,50)
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [62]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [64]:
b
 # b was created as an independent array, it is a matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [66]:
# You can make matrix be to be a list
print(b.flatten())


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [69]:
b.flatten(order='F') # Forant will fill in the column first

array([  1,  51,   2,  52,   3,  53,   4,  54,   5,  55,   6,  56,   7,
        57,   8,  58,   9,  59,  10,  60,  11,  61,  12,  62,  13,  63,
        14,  64,  15,  65,  16,  66,  17,  67,  18,  68,  19,  69,  20,
        70,  21,  71,  22,  72,  23,  73,  24,  74,  25,  75,  26,  76,
        27,  77,  28,  78,  29,  79,  30,  80,  31,  81,  32,  82,  33,
        83,  34,  84,  35,  85,  36,  86,  37,  87,  38,  88,  39,  89,
        40,  90,  41,  91,  42,  92,  43,  93,  44,  94,  45,  95,  46,
        96,  47,  97,  48,  98,  49,  99,  50, 100])

In [75]:
a = np.arange(12)
print(a)



[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [76]:
a.reshape((3,4), order='C') # Fil in row first

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
a.reshape((3,4), order='F') # fill in column first

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

### np transpose

In [81]:
c = b.T # this how to transpose
c

array([[  1,  51],
       [  2,  52],
       [  3,  53],
       [  4,  54],
       [  5,  55],
       [  6,  56],
       [  7,  57],
       [  8,  58],
       [  9,  59],
       [ 10,  60],
       [ 11,  61],
       [ 12,  62],
       [ 13,  63],
       [ 14,  64],
       [ 15,  65],
       [ 16,  66],
       [ 17,  67],
       [ 18,  68],
       [ 19,  69],
       [ 20,  70],
       [ 21,  71],
       [ 22,  72],
       [ 23,  73],
       [ 24,  74],
       [ 25,  75],
       [ 26,  76],
       [ 27,  77],
       [ 28,  78],
       [ 29,  79],
       [ 30,  80],
       [ 31,  81],
       [ 32,  82],
       [ 33,  83],
       [ 34,  84],
       [ 35,  85],
       [ 36,  86],
       [ 37,  87],
       [ 38,  88],
       [ 39,  89],
       [ 40,  90],
       [ 41,  91],
       [ 42,  92],
       [ 43,  93],
       [ 44,  94],
       [ 45,  95],
       [ 46,  96],
       [ 47,  97],
       [ 48,  98],
       [ 49,  99],
       [ 50, 100]])

In [83]:
c = np.transpose(b)
c

array([[  1,  51],
       [  2,  52],
       [  3,  53],
       [  4,  54],
       [  5,  55],
       [  6,  56],
       [  7,  57],
       [  8,  58],
       [  9,  59],
       [ 10,  60],
       [ 11,  61],
       [ 12,  62],
       [ 13,  63],
       [ 14,  64],
       [ 15,  65],
       [ 16,  66],
       [ 17,  67],
       [ 18,  68],
       [ 19,  69],
       [ 20,  70],
       [ 21,  71],
       [ 22,  72],
       [ 23,  73],
       [ 24,  74],
       [ 25,  75],
       [ 26,  76],
       [ 27,  77],
       [ 28,  78],
       [ 29,  79],
       [ 30,  80],
       [ 31,  81],
       [ 32,  82],
       [ 33,  83],
       [ 34,  84],
       [ 35,  85],
       [ 36,  86],
       [ 37,  87],
       [ 38,  88],
       [ 39,  89],
       [ 40,  90],
       [ 41,  91],
       [ 42,  92],
       [ 43,  93],
       [ 44,  94],
       [ 45,  95],
       [ 46,  96],
       [ 47,  97],
       [ 48,  98],
       [ 49,  99],
       [ 50, 100]])

In [84]:
a = np.arange(8)

In [88]:
b = a.reshape(2,2,2)
b

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [89]:
b.ndim

3

### Numpy Arithmetic Operation

In [92]:
a = np.arange(9)
a = a.reshape(3,3)
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
b = np.array(10) # this is scalar
b

array(10)

In [96]:
c = np.add(a,b)
c

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [106]:
d = np.array([2,1,2]) 
print(d)

[2 1 2]


In [107]:
c = np.add(d, a)
c

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [109]:
c = np.subtract(d,a)
c

array([[ 2,  0,  0],
       [-1, -3, -3],
       [-4, -6, -6]])

In [111]:
c = np.multiply(a,d)
c

array([[ 0,  1,  4],
       [ 6,  4, 10],
       [12,  7, 16]])

In [115]:
c = np.multiply(d,a) # pointwise multiplication
c

array([[ 0,  1,  4],
       [ 6,  4, 10],
       [12,  7, 16]])

In [118]:
c = np.divide(a, d)
c

array([[0. , 1. , 1. ],
       [1.5, 4. , 2.5],
       [3. , 7. , 4. ]])

### Slicing Arrays

In [120]:
a = np.arange(20)
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [121]:
a[4:]


array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [122]:
a[9:16:2]

array([ 9, 11, 13, 15])

In [126]:
a[::-1] # This will reverse it

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

### Iterating an array

In [132]:
a = np.arange(20)
a = a.reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [134]:
for i in np.nditer(a):
    print(f'the element here is {i}') # it goes through it row by row

the element here is 0
the element here is 1
the element here is 2
the element here is 3
the element here is 4
the element here is 5
the element here is 6
the element here is 7
the element here is 8
the element here is 9
the element here is 10
the element here is 11
the element here is 12
the element here is 13
the element here is 14
the element here is 15
the element here is 16
the element here is 17
the element here is 18
the element here is 19


In [137]:
print(a)

for i in np.nditer(a, order='C'):
    print(i)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [140]:
for i in np.nditer(a, order='F'): # print using columns
    print(i)

0
10
1
11
2
12
3
13
4
14
5
15
6
16
7
17
8
18
9
19


## Concatenating arrays

In [142]:
a = np.array([[1,2], [3,4]])
b = np.array([[-1,-2], [-3,-4]])


array([[1, 2],
       [3, 4]])

In [150]:
c = np.concatenate((a,b), axis=0) # along the axis 0 which is y
c

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [152]:
c = np.concatenate((a,b), axis=1) # along the axis 1 which is x
c

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

## Spliting Arrays

In [154]:
a = np.arange(9)
np.split(a, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [155]:
np.split(a,[4,5]) # split at position 4 and 5

[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]

In [157]:
np.split(a,[4,5,6]) # split at 4, 5, 6

[array([0, 1, 2, 3]), array([4]), array([5]), array([6, 7, 8])]

## Resizing array

In [167]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
a



array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [175]:
a.resize()
print(a.resize(1,9))

None
