In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


%matplotlib inline

In [2]:
data = pd.read_csv('Social_Network_Ads.csv')
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [3]:
X = data.iloc[ : , : -1].values
y = data.iloc[: , -1].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0) # random state make sure it has the same outcome everytime you run it


#### Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train_scaled = sc_X.fit_transform(X_train)
X_test_scaled = sc_X.fit_transform(X_test)

In [20]:
X_train_scaled

array([[-0.8 , -1.19],
       [ 0.76, -1.37],
       [ 0.85,  1.44],
       [-0.51, -1.49],
       [-1.49,  0.38],
       [-1.19,  0.55],
       [ 1.05, -1.04],
       [-0.22, -0.3 ],
       [ 0.95, -1.34],
       [-1.1 , -1.07],
       [-0.51,  1.97],
       [ 2.22, -1.01],
       [ 1.44, -1.4 ],
       [ 0.07, -0.39],
       [-1.19,  0.64],
       [ 2.02, -0.9 ],
       [ 1.15,  0.58],
       [-0.02,  0.29],
       [-0.22,  0.26],
       [-0.32, -0.75],
       [-1.68, -0.57],
       [ 0.85,  0.58],
       [-0.61, -1.01],
       [ 0.95, -1.13],
       [-0.22, -0.54],
       [ 0.17,  0.82],
       [-0.41,  1.32],
       [ 1.15,  0.52],
       [ 0.76,  0.32],
       [ 0.66, -0.87],
       [ 0.37, -0.27],
       [ 0.46, -0.45],
       [-0.22,  0.14],
       [ 0.37,  0.11],
       [-1.  ,  0.82],
       [-0.71,  1.41],
       [ 0.37, -0.48],
       [ 0.37, -0.48],
       [-1.68,  0.41],
       [ 0.85, -0.81],
       [-1.  , -1.1 ],
       [-0.22,  0.08],
       [ 1.15, -1.19],
       [-0.

### Logistic Regression Classification

In [6]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train_scaled, y_train)

LogisticRegression(random_state=0)

Predict for X_test

In [7]:
y_pred = classifier.predict(X_test_scaled)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [13]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)),1))

[[0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


Predict for age 30 and 800000

In [8]:
X_sample = [[40,90000]]
X_sample_scaled = sc_X.transform(X_sample)
X_sample_scaled

array([[0.32989768, 0.60480202]])

In [9]:
y_sample_predict = classifier.predict(X_sample_scaled)
y_sample_predict

array([1])

#### Confusion Matrix

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm


array([[63,  5],
       [ 8, 24]])

#### Accuracy

In [11]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.87