In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


%matplotlib inline

In [3]:
data = pd.read_csv('possum.csv')
data

case  site    Pop sex  age  hdlngth  skullw  totlngth  taill  footlgth  \
0       1     1    Vic   m  8.0     94.1    60.4      89.0   36.0      74.5   
1       2     1    Vic   f  6.0     92.5    57.6      91.5   36.5      72.5   
2       3     1    Vic   f  6.0     94.0    60.0      95.5   39.0      75.4   
3       4     1    Vic   f  6.0     93.2    57.1      92.0   38.0      76.1   
4       5     1    Vic   f  2.0     91.5    56.3      85.5   36.0      71.0   
..    ...   ...    ...  ..  ...      ...     ...       ...    ...       ...   
99    100     7  other   m  1.0     89.5    56.0      81.5   36.5      66.0   
100   101     7  other   m  1.0     88.6    54.7      82.5   39.0      64.4   
101   102     7  other   f  6.0     92.4    55.0      89.0   38.0      63.5   
102   103     7  other   m  4.0     91.5    55.2      82.5   36.5      62.9   
103   104     7  other   f  3.0     93.6    59.9      89.0   40.0      67.6   

     earconch   eye  chest  belly  
0        54.5  15.2   28.0   36.0  
1        51.2  16.0   28.5   33.0  
2        51.9  15.5   30.0   34.0  
3        52.2  15.2   28.0   34.0  
4        53.2  15.1   28.5   33.0  
..        ...   ...    ...    ...  
99       46.8  14.8   23.0   27.0  
100      48.0  14.0   25.0   33.0  
101      45.4  13.0   25.0   30.0  
102      45.9  15.4   25.0   29.0  
103      46.0  14.8   28.5   33.5  

[104 rows x 14 columns]

In [4]:
# We have to predict the age of possum
print(data.columns)

Index(['case', 'site', 'Pop', 'sex', 'age', 'hdlngth', 'skullw', 'totlngth',
       'taill', 'footlgth', 'earconch', 'eye', 'chest', 'belly'],
      dtype='object')


In [5]:
data = data[['case',  'Pop', 'sex', 'site',  'hdlngth', 'skullw', 'totlngth', 'taill', 'footlgth', 'earconch', 'eye', 'chest', 'belly', 'age']]

In [6]:
data

case    Pop sex  site  hdlngth  skullw  totlngth  taill  footlgth  \
0       1    Vic   m     1     94.1    60.4      89.0   36.0      74.5   
1       2    Vic   f     1     92.5    57.6      91.5   36.5      72.5   
2       3    Vic   f     1     94.0    60.0      95.5   39.0      75.4   
3       4    Vic   f     1     93.2    57.1      92.0   38.0      76.1   
4       5    Vic   f     1     91.5    56.3      85.5   36.0      71.0   
..    ...    ...  ..   ...      ...     ...       ...    ...       ...   
99    100  other   m     7     89.5    56.0      81.5   36.5      66.0   
100   101  other   m     7     88.6    54.7      82.5   39.0      64.4   
101   102  other   f     7     92.4    55.0      89.0   38.0      63.5   
102   103  other   m     7     91.5    55.2      82.5   36.5      62.9   
103   104  other   f     7     93.6    59.9      89.0   40.0      67.6   

     earconch   eye  chest  belly  age  
0        54.5  15.2   28.0   36.0  8.0  
1        51.2  16.0   28.5   33.0  6.0  
2        51.9  15.5   30.0   34.0  6.0  
3        52.2  15.2   28.0   34.0  6.0  
4        53.2  15.1   28.5   33.0  2.0  
..        ...   ...    ...    ...  ...  
99       46.8  14.8   23.0   27.0  1.0  
100      48.0  14.0   25.0   33.0  1.0  
101      45.4  13.0   25.0   30.0  6.0  
102      45.9  15.4   25.0   29.0  4.0  
103      46.0  14.8   28.5   33.5  3.0  

[104 rows x 14 columns]

In [7]:
X = data.iloc[ : , 1: -1].values
y = data.iloc[: , -1].values

In [8]:
X

array([['Vic', 'm', 1, ..., 15.2, 28.0, 36.0],
       ['Vic', 'f', 1, ..., 16.0, 28.5, 33.0],
       ['Vic', 'f', 1, ..., 15.5, 30.0, 34.0],
       ...,
       ['other', 'f', 7, ..., 13.0, 25.0, 30.0],
       ['other', 'm', 7, ..., 15.4, 25.0, 29.0],
       ['other', 'f', 7, ..., 14.8, 28.5, 33.5]], dtype=object)

In [9]:
y

array([ 8.,  6.,  6.,  6.,  2.,  1.,  2.,  6.,  9.,  6.,  9.,  5.,  5.,
        3.,  5.,  4.,  1.,  2.,  5.,  4.,  3.,  3.,  4.,  2.,  3.,  7.,
        2.,  4.,  3.,  2.,  3.,  4.,  3.,  2.,  4.,  7.,  2.,  7.,  1.,
        3.,  5.,  3.,  2., nan,  3., nan,  2.,  5.,  4.,  5.,  5.,  6.,
        3.,  7.,  2.,  3.,  4.,  3.,  2.,  2.,  7.,  3.,  6.,  3.,  5.,
        3.,  4.,  5.,  5.,  7.,  6.,  1.,  1.,  4.,  6.,  5.,  6.,  1.,
        1.,  1.,  3.,  4.,  3.,  3.,  3.,  3.,  2.,  2.,  6.,  3.,  3.,
        2.,  3.,  7.,  4.,  4.,  3.,  5.,  3.,  1.,  1.,  6.,  4.,  3.])

Take care of missing data in X

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 3:]) # find the missing data in column 1 and 2
X[:, 3:] = imputer.transform(X[:, 3:]) # do the replacing
X

array([['Vic', 'm', 1, ..., 15.2, 28.0, 36.0],
       ['Vic', 'f', 1, ..., 16.0, 28.5, 33.0],
       ['Vic', 'f', 1, ..., 15.5, 30.0, 34.0],
       ...,
       ['other', 'f', 7, ..., 13.0, 25.0, 30.0],
       ['other', 'm', 7, ..., 15.4, 25.0, 29.0],
       ['other', 'f', 7, ..., 14.8, 28.5, 33.5]], dtype=object)

Take of the missing data in y

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

y = y.reshape(-1, 1)
imputer.fit(y) 
y = imputer.transform(y) 
y = y.flatten()
y

array([8.        , 6.        , 6.        , 6.        , 2.        ,
       1.        , 2.        , 6.        , 9.        , 6.        ,
       9.        , 5.        , 5.        , 3.        , 5.        ,
       4.        , 1.        , 2.        , 5.        , 4.        ,
       3.        , 3.        , 4.        , 2.        , 3.        ,
       7.        , 2.        , 4.        , 3.        , 2.        ,
       3.        , 4.        , 3.        , 2.        , 4.        ,
       7.        , 2.        , 7.        , 1.        , 3.        ,
       5.        , 3.        , 2.        , 3.83333333, 3.        ,
       3.83333333, 2.        , 5.        , 4.        , 5.        ,
       5.        , 6.        , 3.        , 7.        , 2.        ,
       3.        , 4.        , 3.        , 2.        , 2.        ,
       7.        , 3.        , 6.        , 3.        , 5.        ,
       3.        , 4.        , 5.        , 5.        , 7.        ,
       6.        , 1.        , 1.        , 4.        , 6.     

In [12]:
X

array([['Vic', 'm', 1, ..., 15.2, 28.0, 36.0],
       ['Vic', 'f', 1, ..., 16.0, 28.5, 33.0],
       ['Vic', 'f', 1, ..., 15.5, 30.0, 34.0],
       ...,
       ['other', 'f', 7, ..., 13.0, 25.0, 30.0],
       ['other', 'm', 7, ..., 15.4, 25.0, 29.0],
       ['other', 'f', 7, ..., 14.8, 28.5, 33.5]], dtype=object)

In [13]:
y

array([8.        , 6.        , 6.        , 6.        , 2.        ,
       1.        , 2.        , 6.        , 9.        , 6.        ,
       9.        , 5.        , 5.        , 3.        , 5.        ,
       4.        , 1.        , 2.        , 5.        , 4.        ,
       3.        , 3.        , 4.        , 2.        , 3.        ,
       7.        , 2.        , 4.        , 3.        , 2.        ,
       3.        , 4.        , 3.        , 2.        , 4.        ,
       7.        , 2.        , 7.        , 1.        , 3.        ,
       5.        , 3.        , 2.        , 3.83333333, 3.        ,
       3.83333333, 2.        , 5.        , 4.        , 5.        ,
       5.        , 6.        , 3.        , 7.        , 2.        ,
       3.        , 4.        , 3.        , 2.        , 2.        ,
       7.        , 3.        , 6.        , 3.        , 5.        ,
       3.        , 4.        , 5.        , 5.        , 7.        ,
       6.        , 1.        , 1.        , 4.        , 6.     

Encode Pop and sex columns


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [15]:
# Run this only once
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1])], remainder='passthrough') # column 1, 2 is what we want to encode and passthrough means leave the others
X = np.array(ct.fit_transform(X)) # np.array makes it a matrix 

Split

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1) # random state make sure it has the same outcome everytime you run it


Simple Linear Regression

In [19]:
from sklearn.linear_model import LinearRegression
simple_regressor = LinearRegression()
simple_regressor.fit(X_train, y_train)
simple_pred = simple_regressor.predict(X_test)
simple_pred



array([3.17503525, 3.32307451, 3.94190138, 3.69753476, 2.31937503,
       3.47056449, 6.11862178, 3.86410496, 4.58963891, 5.93501294,
       4.74118672, 2.56414307, 2.38014552, 4.98850695, 2.92006948,
       3.93784502, 4.65448102, 4.6902528 , 3.5957604 , 2.91391551,
       4.1057553 ])

In [20]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), simple_pred.reshape(-1,1)),1))

[[3.   3.18]
 [7.   3.32]
 [4.   3.94]
 [2.   3.7 ]
 [1.   2.32]
 [3.   3.47]
 [7.   6.12]
 [3.   3.86]
 [4.   4.59]
 [4.   5.94]
 [3.   4.74]
 [2.   2.56]
 [2.   2.38]
 [2.   4.99]
 [2.   2.92]
 [6.   3.94]
 [3.   4.65]
 [3.   4.69]
 [2.   3.6 ]
 [6.   2.91]
 [5.   4.11]]


In [21]:
from sklearn.metrics import r2_score
simple_r2_score = r2_score(y_test,  simple_pred)
simple_r2_score

0.020184384288670087

Multiple Linear Regression

In [22]:
from sklearn.linear_model import LinearRegression
multiple_regressor = LinearRegression()
multiple_regressor.fit(X_train, y_train) 
multiple_pred = multiple_regressor.predict(X_test)
multiple_pred

array([3.18, 3.32, 3.94, 3.7 , 2.32, 3.47, 6.12, 3.86, 4.59, 5.94, 4.74,
       2.56, 2.38, 4.99, 2.92, 3.94, 4.65, 4.69, 3.6 , 2.91, 4.11])

In [23]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), multiple_pred.reshape(-1,1)),1))

[[3.   3.18]
 [7.   3.32]
 [4.   3.94]
 [2.   3.7 ]
 [1.   2.32]
 [3.   3.47]
 [7.   6.12]
 [3.   3.86]
 [4.   4.59]
 [4.   5.94]
 [3.   4.74]
 [2.   2.56]
 [2.   2.38]
 [2.   4.99]
 [2.   2.92]
 [6.   3.94]
 [3.   4.65]
 [3.   4.69]
 [2.   3.6 ]
 [6.   2.91]
 [5.   4.11]]


In [24]:
from sklearn.metrics import r2_score
multiple_r2_score = r2_score(y_test,  multiple_pred)
multiple_r2_score

0.020184384288670087

Polynomial Regression

In [30]:
from sklearn.preprocessing import PolynomialFeatures 
poly_converter= PolynomialFeatures(degree=5)  # convert the X_train to degree 4 
X_train_poly = poly_converter.fit_transform(X_train) # convert the X_test to degree 4 
X_test_poly = poly_converter.fit_transform(X_test)

In [31]:
from sklearn.linear_model import LinearRegression
poly_regressor = LinearRegression()
poly_regressor.fit(X_train_poly, y_train)
poly_pred = poly_regressor.predict(X_test_poly)
poly_pred

array([ 0.66, 16.5 , -0.02,  4.85,  1.75,  7.87,  4.32,  5.18, 10.6 ,
       12.98,  6.45, -0.35,  1.4 , 15.44,  3.15,  1.47,  7.18, -4.03,
        3.19, -1.79,  5.05])

In [28]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), poly_pred.reshape(-1,1)),1))

[[ 3.00e+00  8.09e-01]
 [ 7.00e+00  1.60e+01]
 [ 4.00e+00  8.14e-04]
 [ 2.00e+00  5.07e+00]
 [ 1.00e+00  2.29e+00]
 [ 3.00e+00  7.89e+00]
 [ 7.00e+00  2.62e+00]
 [ 3.00e+00  6.04e+00]
 [ 4.00e+00  1.05e+01]
 [ 4.00e+00  1.28e+01]
 [ 3.00e+00  6.56e+00]
 [ 2.00e+00 -2.96e-01]
 [ 2.00e+00  1.43e+00]
 [ 2.00e+00  1.64e+01]
 [ 2.00e+00  2.63e+00]
 [ 6.00e+00  2.38e+00]
 [ 3.00e+00  7.22e+00]
 [ 3.00e+00 -3.64e+00]
 [ 2.00e+00  3.12e+00]
 [ 6.00e+00 -6.10e-01]
 [ 5.00e+00  4.22e+00]]


In [32]:
from sklearn.metrics import r2_score
poly_r2_score = r2_score(y_test,  poly_pred)
poly_r2_score

-9.28245692898424

Support Vector Regression

In [33]:
# We do the feature scaling for both X and y sets
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train_scaled = sc_X.fit_transform(X_train)
X_test_scaled = sc_X.fit_transform(X_test)

In [34]:
# Reshape y before scaling
sc_y = StandardScaler()
y_train_trans = y_train.reshape(-1, 1)
y_train_scaled = sc_y.fit_transform(y_train_trans)

In [35]:
from sklearn.svm import SVR
svr_regressor = SVR(kernel='rbf') # always use rbf
svr_regressor.fit(X_train_scaled, y_train_scaled) # train on the scaled model
# ignore the 1-d error

/Users/user/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [36]:
svr_pred_scaled = svr_regressor.predict(X_test_scaled)
svr_pred_scaled = svr_pred_scaled.reshape(-1, 1) # so it can be easily inverted


In [37]:
# Ger the inverse
svr_pred = sc_y.inverse_transform(svr_pred_scaled)
svr_pred = svr_pred.flatten()
svr_pred

array([3.2 , 4.47, 3.09, 4.03, 2.62, 2.73, 2.96, 3.65, 5.54, 4.07, 4.97,
       3.85, 3.45, 1.94, 3.47, 4.79, 4.03, 5.44, 3.52, 3.75, 4.81])

In [38]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), svr_pred.reshape(-1,1)),1))

[[3.   3.2 ]
 [7.   4.47]
 [4.   3.09]
 [2.   4.03]
 [1.   2.62]
 [3.   2.73]
 [7.   2.96]
 [3.   3.65]
 [4.   5.54]
 [4.   4.07]
 [3.   4.97]
 [2.   3.85]
 [2.   3.45]
 [2.   1.94]
 [2.   3.47]
 [6.   4.79]
 [3.   4.03]
 [3.   5.44]
 [2.   3.52]
 [6.   3.75]
 [5.   4.81]]


In [39]:
from sklearn.metrics import r2_score
svr_r2_score = r2_score(y_test,  svr_pred)
svr_r2_score

0.008622487783643717

Decison Tree

In [40]:
from sklearn.tree import DecisionTreeRegressor
tree_regressor = DecisionTreeRegressor(random_state=1)
tree_regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=1)

In [41]:
tree_pred = tree_regressor.predict(X_test)
tree_pred

array([3., 4., 4., 2., 3., 2., 3., 3., 6., 3., 6., 3., 2., 3., 3., 7., 6.,
       3., 9., 3., 4.])

In [42]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), tree_pred.reshape(-1,1)),1))

[[3. 3.]
 [7. 4.]
 [4. 4.]
 [2. 2.]
 [1. 3.]
 [3. 2.]
 [7. 3.]
 [3. 3.]
 [4. 6.]
 [4. 3.]
 [3. 6.]
 [2. 3.]
 [2. 2.]
 [2. 3.]
 [2. 3.]
 [6. 7.]
 [3. 6.]
 [3. 3.]
 [2. 9.]
 [6. 3.]
 [5. 4.]]


In [43]:
from sklearn.metrics import r2_score
tree_r2_score = r2_score(y_test,  tree_pred)
tree_r2_score

-0.8942457231726282

Random Forest Regression

In [44]:
from sklearn.ensemble import RandomForestRegressor
forest_regressor = RandomForestRegressor(n_estimators=10, random_state=0) # numbers of trees to be used
forest_regressor.fit(X_train, y_train)
forest_pred = forest_regressor.predict(X_test)
forest_pred

array([2.8 , 4.4 , 1.4 , 3.6 , 2.85, 2.5 , 3.6 , 1.6 , 5.2 , 4.8 , 5.6 ,
       2.3 , 2.1 , 3.7 , 2.48, 5.3 , 4.9 , 3.08, 6.5 , 2.9 , 5.3 ])

In [45]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), forest_pred.reshape(-1,1)),1))


[[3.   2.8 ]
 [7.   4.4 ]
 [4.   1.4 ]
 [2.   3.6 ]
 [1.   2.85]
 [3.   2.5 ]
 [7.   3.6 ]
 [3.   1.6 ]
 [4.   5.2 ]
 [4.   4.8 ]
 [3.   5.6 ]
 [2.   2.3 ]
 [2.   2.1 ]
 [2.   3.7 ]
 [2.   2.48]
 [6.   5.3 ]
 [3.   4.9 ]
 [3.   3.08]
 [2.   6.5 ]
 [6.   2.9 ]
 [5.   5.3 ]]


In [46]:
from sklearn.metrics import r2_score
forest_r2_score = r2_score(y_test,  forest_pred)
forest_r2_score

-0.29711832555728357

In [47]:
performance_dict = {
    'simple linear regression': round(simple_r2_score, 4),
    'multiple linear regression': round(multiple_r2_score, 4),
    'polynomial regression': round(poly_r2_score, 4),
    'support vector regression': round(svr_r2_score, 4),
    'decision tree regression': round(tree_r2_score, 4),
    'random forest regression': round(forest_r2_score, 4),
}

score_list = []

for key,value in performance_dict.items():
    score_list.append(value)
    max_score = max(score_list)

for key,value in performance_dict.items():
    if value == max_score:
        print(f'The best performing model is {key}')

The best performing model is simple linear regression
The best performing model is multiple linear regression
