In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


%matplotlib inline

In [2]:
data = pd.read_csv('data.csv')
data

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000       70    2.707  0.467409   8.8071     9.702400   
1     83  20.690495       92    3.115  0.706897   8.8438     5.429285   
2     82  23.124670       91    4.498  1.009651  17.9393    22.432040   
3     68  21.367521       77    3.226  0.612725   9.8827     7.169560   
4     86  21.111111       92    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
111   45  26.850000       92    3.330  0.755688  54.6800    12.100000   
112   62  26.840000      100    4.530  1.117400  12.4500    21.420000   
113   65  32.050000       97    5.730  1.370998  61.4800    22.540000   
114   72  25.590000       82    2.820  0.570392  24.9600    33.750000   
115   86  27.180000      138   19.910  6.777364  90.2800    14.110000   

     Resistin    MCP.1  Classification  
0     7.99585  417.114               1  
1     4.06405  468.786               1  
2     9.27715  554.697               1  
3    12.76600  928.220               1  
4    10.57635  773.920               1  
..        ...      ...             ...  
111  10.96000  268.230               2  
112   7.32000  330.160               2  
113  10.33000  314.050               2  
114   3.27000  392.460               2  
115   4.35000   90.090               2  

[116 rows x 10 columns]

In [3]:
X = data.iloc[ : , : -1].values
y = data.iloc[: , -1].values

In [4]:
X

array([[ 48.        ,  23.5       ,  70.        , ...,   9.7024    ,
          7.99585   , 417.114     ],
       [ 83.        ,  20.69049454,  92.        , ...,   5.429285  ,
          4.06405   , 468.786     ],
       [ 82.        ,  23.12467037,  91.        , ...,  22.43204   ,
          9.27715   , 554.697     ],
       ...,
       [ 65.        ,  32.05      ,  97.        , ...,  22.54      ,
         10.33      , 314.05      ],
       [ 72.        ,  25.59      ,  82.        , ...,  33.75      ,
          3.27      , 392.46      ],
       [ 86.        ,  27.18      , 138.        , ...,  14.11      ,
          4.35      ,  90.09      ]])

In [5]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0) # random state make sure it has the same outcome everytime you run it


In [7]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train_scaled = sc_X.fit_transform(X_train)
X_test_scaled = sc_X.fit_transform(X_test)

In [8]:
from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression()
logistic_classifier.fit(X_train_scaled, y_train)

LogisticRegression()

In [9]:
logistic_pred = logistic_classifier.predict(X_test_scaled)
logistic_pred

array([1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 1, 1, 1])

In [10]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), logistic_pred.reshape(-1,1)),1))

[[1 1]
 [2 2]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [2 1]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [1 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 1]
 [1 1]]


In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
logistic_cm = confusion_matrix(y_test, logistic_pred)
logistic_cm 


array([[ 9,  3],
       [ 6, 11]])

In [12]:
logistic_accuracy = accuracy_score(y_test,logistic_pred)
logistic_accuracy

0.6896551724137931

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
knn_classifier.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [14]:
knn_pred = knn_classifier.predict(X_test_scaled)
knn_pred

array([1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1,
       1, 2, 2, 2, 1, 2, 1])

In [15]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), knn_pred.reshape(-1,1)),1))

[[1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 2]
 [1 1]]


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
knn_cm = confusion_matrix(y_test, knn_pred)
knn_cm


array([[11,  1],
       [ 3, 14]])

In [17]:
knn_accuracy = accuracy_score(y_test,knn_pred)
knn_accuracy

0.8620689655172413

In [18]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel='linear', random_state=0)
svm_classifier.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=0)

In [19]:
svm_pred = svm_classifier.predict(X_test_scaled)
svm_pred

array([1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 1, 1, 1])

In [20]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), svm_pred.reshape(-1,1)),1))

[[1 1]
 [2 1]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [2 1]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [1 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 1]
 [1 1]]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
svm_cm = confusion_matrix(y_test, svm_pred)
svm_cm


array([[10,  2],
       [ 7, 10]])

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
svm_accurarcy = accuracy_score(y_test, svm_pred)
svm_accurarcy



0.6896551724137931

In [23]:
from sklearn.svm import SVC
svmk_classifier = SVC(kernel='rbf', random_state=0)
svmk_classifier.fit(X_train_scaled, y_train)

SVC(random_state=0)

In [24]:
svmk_pred = svmk_classifier.predict(X_test_scaled)
svmk_pred

array([1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1,
       1, 2, 2, 2, 1, 1, 1])

In [25]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), svmk_pred.reshape(-1,1)),1))

[[1 1]
 [2 2]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [2 2]
 [2 2]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 1]
 [1 1]]


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
svmk_cm = confusion_matrix(y_test, svmk_pred)
svmk_cm


array([[ 9,  3],
       [ 5, 12]])

In [27]:
smvk_accuracy = accuracy_score(y_test,svmk_pred)
smvk_accuracy

0.7241379310344828

In [28]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train_scaled, y_train)


GaussianNB()

In [29]:
nb_pred = nb_classifier.predict(X_test_scaled)
nb_pred

array([1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1])

In [30]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), nb_pred.reshape(-1,1)),1))

[[1 1]
 [2 2]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [2 1]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [2 2]
 [2 1]
 [2 1]
 [2 1]
 [1 1]]


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
nb_cm = confusion_matrix(y_test, nb_pred)
nb_cm


array([[11,  1],
       [10,  7]])

In [32]:
nb_accuracy = accuracy_score(y_test,nb_pred)
nb_accuracy

0.6206896551724138

In [33]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
tree_classifier.fit(X_train_scaled, y_train)


DecisionTreeClassifier(criterion='entropy', random_state=0)

In [34]:
tree_pred = tree_classifier.predict(X_test_scaled)
tree_pred

array([1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1,
       1, 2, 1, 2, 2, 1, 1])

In [35]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), tree_pred.reshape(-1,1)),1))

[[1 1]
 [2 1]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [2 1]
 [2 2]
 [2 1]
 [2 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [2 2]
 [2 2]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [2 1]
 [2 2]
 [2 2]
 [2 1]
 [1 1]]


In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
tree_cm = confusion_matrix(y_test, tree_pred)
tree_cm

array([[ 9,  3],
       [ 7, 10]])

In [37]:
tree_accuracy = accuracy_score(y_test,tree_pred)
tree_accuracy

0.6551724137931034

In [38]:
from sklearn.ensemble import RandomForestClassifier
forest_classifier = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
forest_classifier.fit(X_train_scaled, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [39]:
forest_pred = forest_classifier.predict(X_test_scaled)
forest_pred

array([1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1,
       2, 2, 2, 2, 1, 1, 1])

In [40]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), forest_pred.reshape(-1,1)),1))

[[1 1]
 [2 1]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [2 1]
 [2 2]
 [2 1]
 [2 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 1]
 [1 1]]


In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
forest_cm = confusion_matrix(y_test, forest_pred)
forest_cm


array([[ 9,  3],
       [ 7, 10]])

In [42]:
forest_accuracy = accuracy_score(y_test, forest_pred)
forest_accuracy

0.6551724137931034

In [43]:
performance_dict = {
    'logistic regression classification': round(logistic_accuracy, 4),
    'K nearest neighbor classification': round(knn_accuracy, 4),
    'simple vector model classification': round(svm_accurarcy, 4),
    'simple vector model kernel classification': round(smvk_accuracy, 4),
    'naive bayes classification': round(nb_accuracy, 4),
    'decision tree classification': round(tree_accuracy, 4),
    'random forest classification': round(forest_accuracy, 4),

    
}

score_list = []

for key,value in performance_dict.items():
    score_list.append(value)
    max_score = max(score_list)

for key,value in performance_dict.items():
    if value == max_score:
        print(f'The best performing model is {key}')

The best performing model is K nearest neighbor classification
